version: "3"
services:
  frontend:
    image: httpd:latest
    # Permission
    #command: "chown -R www-data:www-data /usr/local/apache2/htdocs && chmod -R 755 /usr/local/apache2/htdocs"
    volumes:
      - "/root/docker-repo/frontend:/usr/local/apache2/htdocs"
    ports:
      - 3000:80
  backend:
    container_name: simple-backend
    build:
      context: /root/docker-repo/
      dockerfile: Dockerfile
      # Permission
    command: "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html"  
    volumes:
      - "/root/docker-repo/api:/var/www/html/"
    ports:
      - 5000:80
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_admin
      MYSQL_PASSWORD: Sumit123
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      #Permission
      #command: "chown -R www-data:www-data /var/www/html && chmod -R 755 /docker-entrypoint-initdb.d"  
    volumes:
      - "/root/docker-repo/db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
